### ISSUE TITLE
Make it pretty.

### ISSUE THREAD

**Issue by jswanner** [jswanner/RailsDiff#3]

**Comment by jatinganhotra** [comment]
Hi,
I came to know about RailsDiff in the Ruby5 podcast. When I gave it a try, the output was not great.

### I thought of making it pretty by adding jQuery Accordion for each file, so that the user can look at the diffs for each file.

I cloned the repo, made changes in the templates/diff.html.erb file and included the js file.
As you had mentioned, rake gen_diffs works only when the files are not there. So, I deleted all the files in the html/ directory.
Now, when I ran rake gen_diffs, it only generated some of the files and throwed some bug error.

> You may have encountered a bug in the Ruby interpreter or extension libraries.
> Bug reports are welcome.
> For details: http://www.ruby-lang.org/bugreport.html

However, I could see my changes in some of the html files that were generated. But, it didn't work.

### Can you list down the steps, or explain what am I missing.

**Comment by jswanner** [comment]
Hey @silverSpoon, thanks for wanting to help out with the project.

Generating the HTML files, only depends on there being a related .diff file. In order to know which versions of Rails exist, `gen_diffs` needs to look at all the tags in a Rails repository; so you should have a `tmp/rails/rails` directory, which will contain the Rails repo.

First let's start with a simpler Rake task, try running `rake html/v3.0.0-v3.2.8.html` and see if the file is generated. If it is, then we know that part of `gen_diffs` is working. The only other part of `gen_diffs` is the Rails repo, try something like:

``` sh
$ cd tmp/rails/rails
$ git remote fetch
$ git checkout master
```

And, then see if `gen_diffs` works for you.

**Comment by jswanner** [comment]
While I wouldn't mind the site looking better than it currently does, it certainly looks better now than when I opened this issue.

Closing for now, design change PRs welcome.
