### ISSUE TITLE
Update for Rails 4

### ISSUE THREAD

**Issue by olivierlacan** [jswanner/RailsDiff#4]
Tried to figure out how to update this for Rails 4. 

Could you add instructions on how to update/add diffs?

**Comment by jswanner** [comment]
To generate diffs:

``` sh
$ rake
```

That said, the process of generating diffs is currently based on Git tags, and no tag has been created for Rails 4 yet. So, it's currently not possible. I'd hate to have an option called `master` or something, because in order for that to be accurate, it would need to be updated 20-40 times a day.

**Comment by jswanner** [comment]
https://github.com/jswanner/RailsDiff/commit/b3df978c8f39cc0d84c59c31b55316e399211102
